### ISSUE TITLE
Spike: trial desired campaign audience exclusion rules via API

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail-newsletter#7]
We need to confirm we can reproduce what the Mailchimp campaign creation UI provides – with the API. Excluding specific sub-segments seems trickier than we initially expected.

## Notes from research so far

Looking at [POST /campaigns](https://mailchimp.com/developer/marketing/api/campaigns/add-campaign/) > `recipients` > `segment_opts` > `conditions` – reviewing the [condition schemas](https://mailchimp.com/developer/marketing/docs/alternative-schemas/#segment-condition-schemas) – the `op` operators have "not" options which I’d assume work as exclude?

For example the `StaticSegment` condition type supports an op of `static_not`, `Interests` has `interestnotcontains`?

---

The UI's "Do not send to" option is not reflected in the API – neither the selected choice, nor the number of recipients. It very much feels like it operates at a different level.
The StaticSegment condition doesn't map to audience segments – TBH I don't understand what it maps to.
But it's possible to express simple exclusion rules in the recipients > segment_opts > conditions list, so let's see what FPF's exclusion rules are.

**Comment by mgax** [comment]
We need to figure out if we can emulate the _exclusion of a certain tag_ that's defined in the audience.

**Comment by mgax** [comment]
Hopefully FPF can reconfigure the segments to incorporate any exclusion rules. If that turns out to be impractical, we can reopen this ticket and look for alternatives.
